### PR TITLE
Michael Valenzuela - Completed css-canvas-medical

### PR DESCRIPTION
**Pull request by michaelvalenzuela**
image

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Great initial submission, here is my feedback: 

Feedback for Canvas Medical
For the Nav: 
	the color of the Canvas Icon and the contact us “button” must be adjusted
For the image: 
	Font size for the heading should be increased
	The paragraph text should have an increased line height
	the get started button should be slightly taller with the updated color
For the clinician section:
	background color should be lighter
	Text should be lighter
	space between items should be increased
Ready to learn section:
	text should be lighter
	get started button should be taller and the color should be adjusted
Footer:
	background should be a little lighter
	missing selection under “product”
	section should be a little taller

**Comment by michaelvalenzuela** [comment]
image

**Review by Zhiwutian — APPROVED** [review]
Looks great Michael, The only thing else I recommend looking up is the `filter` CSS property to lighten the main image a bit. I am sorry for not mentioning it on your first submission. Approved!

**Comment by michaelvalenzuela** [comment]
No worries. I appreciate the feedback and will look into filter 👍

**Pull request merged**
